### ISSUE TITLE
Meaning of the devel branch

### ISSUE THREAD

**Issue by dedekind** [01org/bmap-tools#23]
What is the meaning of the devel branch? I see that master is ahead of it. Should devel be a superset of master, not a subset of it?

**Comment by dedekind** [comment]
Just to explain: a colleague of min showed me a bmaptool bug. He is using the latest and greatest, as he assumes, the devel branch. However, it is behind master, and the bug is actually fixed in master by the "3840b22 TransRead: Fix differentiating between local files and urllib (#22)" commit. I got confused first too. So it is unclear what 'devel' is supposed to be, but it is not what me and the colleagues assumed it to be.

**Comment by kad** [comment]
Branch devel was from pre-github era, and in reality doesn't work well with github PRs workflow.
Removed that stale branch.
